"""Catalog item business logic (create, update, delete, search)"""
from typing import Optional, List, Dict, Any
from sqlalchemy.orm import Session
from sigmaprice.db.models import CatalogItem as CatalogItemModel
from sigmaprice.core.types import RawItem, MatchResult
from sigmaprice.core.exceptions import ValidationError, DatabaseError
from sigmaprice.core.logger import get_logger
from sigmaprice.catalog.code_generator import generate_code
from sigmaprice.catalog.name_builder import build_name
from sigmaprice.catalog.validators import (
    validate_name,
    validate_ean,
    determine_delivery_type,
    is_excluded_delivery,
)
from sigmaprice.catalog.categories import determine_category

logger = get_logger(__name__)

FORBIDDEN_UPDATE_FIELDS = {"id", "code", "created_at", "updated_at"}


def create_item(
    item: RawItem,
    match_result: MatchResult,
    session: Optional[Session] = None,
) -> CatalogItemModel:
    """
    Create a new catalog item from RawItem and MatchResult.

    Algorithm:
    1. Check for excluded delivery types
    2. Generate unique 8-digit code
    3. Build normalized name
    4. Determine category
    5. Determine delivery type
    6. Save to DB
    7. Generate embedding (delegated to caller or triggered separately)

    Raises:
        ValidationError: if required fields are empty
        DatabaseError: if code generation fails after max retries
    """
    from sigmaprice.core.database import get_session
    if session is None:
        session = get_session()

    name = validate_name(item.name)

    if is_excluded_delivery(name):
        raise ValidationError(
            f"Item excluded due to damaged/defective packaging: {name}"
        )

    code = generate_code(session)

    category_id = determine_category(item, session)

    category_name = _get_category_name(category_id, session)
    normalized_name = build_name(item, category_name)

    delivery_type = determine_delivery_type(
        item.name, getattr(item, 'delivery_type', None)
    )

    try:
        catalog_item = CatalogItemModel(
            code=code,
            name=normalized_name,
            description=item.description,
            manufacturer=item.manufacturer,
            article=item.article,
            ean=validate_ean(item.ean),
            category_id=category_id,
            country_origin=getattr(item, 'country_origin', None),
            delivery_type=delivery_type,
        )
        session.add(catalog_item)
        session.flush()

        _save_supplier_mapping(catalog_item.id, item, session)

        session.commit()
        session.refresh(catalog_item)

        logger.info(
            f"Created catalog item: {catalog_item.code} - {catalog_item.name}"
        )
        return catalog_item

    except Exception as e:
        session.rollback()
        logger.error(f"Failed to create catalog item: {e}")
        raise DatabaseError(f"Failed to create catalog item: {e}")


def get_item(
    item_id: int,
    session: Optional[Session] = None,
) -> Optional[CatalogItemModel]:
    """Get catalog item by ID."""
    from sigmaprice.core.database import get_session
    if session is None:
        session = get_session()
    return (
        session.query(CatalogItemModel)
        .filter(CatalogItemModel.id == item_id)
        .first()
    )


def get_item_by_code(
    code: str,
    session: Optional[Session] = None,
) -> Optional[CatalogItemModel]:
    """Get catalog item by 8-digit code."""
    from sigmaprice.core.database import get_session
    if session is None:
        session = get_session()
    return (
        session.query(CatalogItemModel)
        .filter(CatalogItemModel.code == code)
        .first()
    )


def get_item_by_article(
    article: str,
    session: Optional[Session] = None,
) -> Optional[CatalogItemModel]:
    """Get catalog item by article number."""
    from sigmaprice.core.database import get_session
    if session is None:
        session = get_session()
    return (
        session.query(CatalogItemModel)
        .filter(CatalogItemModel.article == article)
        .first()
    )


def update_item(
    item_id: int,
    session: Optional[Session] = None,
    **kwargs,
) -> CatalogItemModel:
    """
    Update catalog item fields.

    Allowed fields:
        name, description, our_price, rrp, warranty_months,
        manufacturer, article, ean, category_id, product_url,
        country_origin, delivery_type

    Forbidden fields:
        code, id, created_at, updated_at

    When name is changed, embedding must be regenerated by caller.
    """
    from sigmaprice.core.database import get_session
    if session is None:
        session = get_session()

    item = (
        session.query(CatalogItemModel)
        .filter(CatalogItemModel.id == item_id)
        .first()
    )
    if not item:
        raise ValidationError(f"Catalog item with ID {item_id} not found")

    for field in FORBIDDEN_UPDATE_FIELDS:
        if field in kwargs:
            raise ValidationError(
                f"Field '{field}' cannot be updated"
            )

    if "ean" in kwargs:
        kwargs["ean"] = validate_ean(kwargs["ean"])

    if "name" in kwargs:
        kwargs["name"] = validate_name(kwargs["name"])

    for key, value in kwargs.items():
        if hasattr(item, key):
            setattr(item, key, value.strip() if isinstance(value, str) else value)

    session.commit()
    session.refresh(item)

    logger.info(f"Updated catalog item: {item.code} (ID: {item.id})")
    return item


def delete_item(
    item_id: int,
    session: Optional[Session] = None,
) -> bool:
    """
    Delete a catalog item.

    Cascades:
    - item_embeddings (via FK ondelete=CASCADE)
    - supplier_item_mapping (via FK ondelete=CASCADE)

    Does NOT delete:
    - supplier_items (catalog_item_id set to NULL)
    - price_history

    Returns True if deleted, False if not found.
    """
    from sigmaprice.core.database import get_session
    from sigmaprice.db.models import SupplierItem

    if session is None:
        session = get_session()

    item = (
        session.query(CatalogItemModel)
        .filter(CatalogItemModel.id == item_id)
        .first()
    )
    if not item:
        return False

    session.query(SupplierItem).filter(
        SupplierItem.catalog_item_id == item_id
    ).update({SupplierItem.catalog_item_id: None})

    item_code = item.code
    session.delete(item)
    session.commit()

    logger.info(f"Deleted catalog item: {item_code} (ID: {item_id})")
    return True


def list_items(
    filters: Optional[Dict[str, Any]] = None,
    session: Optional[Session] = None,
) -> List[CatalogItemModel]:
    """
    List catalog items with optional filters.

    Supported filters:
        category_id: int
        manufacturer: str
        article: str
        delivery_type: str
        search: str (partial name match)
    """
    from sigmaprice.core.database import get_session
    if session is None:
        session = get_session()

    query = session.query(CatalogItemModel)

    if filters:
        if "category_id" in filters:
            query = query.filter(
                CatalogItemModel.category_id == filters["category_id"]
            )
        if "manufacturer" in filters:
            query = query.filter(
                CatalogItemModel.manufacturer.ilike(
                    f"%{filters['manufacturer']}%"
                )
            )
        if "article" in filters:
            query = query.filter(
                CatalogItemModel.article == filters["article"]
            )
        if "delivery_type" in filters:
            query = query.filter(
                CatalogItemModel.delivery_type == filters["delivery_type"]
            )
        if "search" in filters:
            query = query.filter(
                CatalogItemModel.name.ilike(f"%{filters['search']}%")
            )

    return query.order_by(CatalogItemModel.name).all()


def _get_category_name(category_id: int, session: Session) -> str:
    from sigmaprice.db.models import Category
    cat = session.query(Category).filter(Category.id == category_id).first()
    return cat.name if cat else ""


def _save_supplier_mapping(
    catalog_item_id: int,
    item: RawItem,
    session: Session,
) -> None:
    """Save supplier code to catalog item mapping."""
    from sigmaprice.db.models import SupplierItemMapping

    mapping = SupplierItemMapping(
        catalog_item_id=catalog_item_id,
        supplier_id=item.supplier_id,
        supplier_code=item.supplier_code,
    )
    session.add(mapping)
